apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    #instanceTypes: ["m5.large", "c3.large","c4.large","c5.large","t3.medium"]
    instanceTypes: ["c7i-flex.large", "m7i-flex.large"]
    desiredCapacity: 3
    spot: true